export const mapClasses =[
    "variant-1",
    "variant-2",
    "variant-3",
    "variant-1",
    "variant-2",
    "variant-3",
    "variant-1",
    "variant-2",
    "variant-3",
    "variant-1",
];
export const previews = [
    {
        img:'./wallpaper/main-1.jpg',
        title:'one',
        tags:'fashion',
        description:'hdghdhshshggddhdhdhududud'
    },
    {
        img:'./wallpaper/main-2.jpg',
        title:'two',
        tags:'genres',
        description:'gdhdshdgdhdhdu'
    },
    {
        img:'./wallpaper/main-3.jpg',
        title:'three',
        tags:'google',
        description:'gdhdusushs'
    },
    {
        img:'./wallpaper/main-4.jpg',
        title:'four',
        tags:'hdhdh',
        description:'hfhjdhjd'
    },
    {
        img:'./wallpaper/main-5.jpg',
        title:'five',
        tags:'hhdhdj',
        description:'bhdjdjjd'
    },
    {
        img:'./wallpaper/main-6.jpg',
        title:'six',
        tags:'hdhjdhj',
        description:'ghdhdudsududud'
    },
    {
        img:'./wallpaper/main-7.jpg',
        title:'seven',
        tags:'hjdj',
        description:'ndndnjd'
    },
    {
        img:'./wallpaper/main-8.jpg',
        title:'eight',
        tags:'bdhdhddhd',
        description:'dhddhdhh'
    },
    {
        img:'./wallpaper/main-9.jpg',
        title:'nine',
        tags:'bxhhh',
        description:'ghvhdhgavkhay'
    },
    {
        img:'./wallpaper/main-10.jpg',
        title:'ten',
        tags:'bdhdhd',
        description:'hdjdj'
    }
]